# **APC308 - Data Mining**

## Lab2: NumPy Practice Questions



* Write your code in the code cells given under each question.


* Save your notebook as **Lab2-NumPy-yourRegistrationNumber.ipynb**.


* Submission instructions shall be given. 


In [5]:
import numpy as np

#### 1. Create a 1D array of the first 100 integer numbers. 

In [8]:
OneD_array = np.arange(100)
OneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 2. Create an array of integers beween 100 and 120  and display them in reverse order. 

In [11]:
my_array = np.arange(100,120)
print("Atual Array is :",my_array)
res = my_array[::-1]
print("Resultant new reversed array:",res)

Atual Array is : [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]
Resultant new reversed array: [119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103 102
 101 100]


#### 3. Create a 10x10 matrix of the first 100 integer numbers. 

In [23]:

array = np.random.randint(100, size=(10, 10))
print(array)

[[83 46  3 33 19 46 17 60 40  8]
 [74 92 22 54  2 93  4 74 57 78]
 [56  4 47 70 51 56  8 49 54 80]
 [73 76 71 16 88 82 72 43  2 19]
 [78 75 46 53 95 45 65 96 34 28]
 [27  3 41 72 82 36 19 69 45 59]
 [36  4  5 58 12 31 42 70  1 28]
 [15 77 22 13  2 62 51 29 86 44]
 [43 14 92  9  1 80 49 27  7  2]
 [73 75 89 17 68 47 42 68 36 48]]


#### 4. Create three 10x10 matrices of all zeroes, all ones, and the identity matrix. 

In [43]:
D1 = np.zeros((10,10)) 
D2 = np.ones((10,10)) 
D3 = np.identity(10)
D1, D2, D3


(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

#### 5. Create a 3x3 matrix of random floating point values. 

In [30]:
random_3_matrix_array = np.random.rand(3, 3)
print(random_3_matrix_array)

[[0.72289212 0.21088962 0.54714404]
 [0.49522377 0.08257153 0.70146016]
 [0.76793742 0.11940526 0.87244618]]


#### 6. Generate 10 evenly-spaced numbers between 1 and 4. 

In [33]:
 np.linspace(1, 4, num=10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

#### 7. Given the following array named M, slice and display just [4, 6].

In [40]:
M = np.array([ [1,   3,  5], [2,  4 ,  6], [7, 9, 11] ])
M

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 7,  9, 11]])

In [42]:
M[1:1 , 1:]

array([], shape=(0, 2), dtype=int32)

#### 8. Given the above array M, slice and display the sub matrix [ [3, 5], [4, 6] ]. 

#### 9. Display both the column-wise and row-wise sums of M i.e. [10, 16, 22] and [9, 12, 27] respectively. 

#### 10. Flatten M to a 1D array using appropriate  method. 

#### 11. Find the <font color='orange'>second</font> largest number in a given matrix. Use your own matrix. 

#### 12. Multiply a 3x2 matrix with a 2x3 matrix (in at least two ways). 

#### 13. Given a matrix, display all its elements exceeding the median value. 

#### 14. Compute the following hypothetical value. Assume ```i```  is each element of M, ```mean``` and ```std``` are the aggregate mean and standard deviation values of M. 
$$ result = \sqrt{\frac{mean + i} {std} }  $$

#### 15. Given the following formula for a certain parameter named Mean Square Error (MSE), use NumPy to compute its value. 


$$ MSE = \frac{1}{n} \sum_{i=1}^{n}(x_i-y_i)^2 $$


In [ ]:
# you are given the values of x and y below. Assume 'n' is the total no of elements.  

x = np.arange(20)
y = np.random.uniform(1, 10, 20)                        

# MSE = ?? 

