In [1]:
!pip install numpy

In [2]:
import numpy as np

In [77]:
L1 = [1,2,3,4,5]
L2 = [ i*4 for i in L1 ]
L1, L2

([1, 2, 3, 4, 5], [4, 8, 12, 16, 20])

In [78]:
L1*2                    

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [79]:
print(type(L1))

<class 'list'>


In [80]:
A2 = np.array([10,20,30,40,50])
print(A2)

[10 20 30 40 50]


In [81]:
print (type(A2))

<class 'numpy.ndarray'>


In [82]:
A1 = np.array([1,2,3,4], dtype="float")
A2 = np.array([i for i in range(10)])
A3 = np.array([ [1,2,3], [4,5,6] ])
A4 = np.random.rand(4,4)
A1, A2, A3, A4

(array([1., 2., 3., 4.]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0.17509297, 0.41572507, 0.165431  , 0.90549746],
        [0.08860702, 0.19036629, 0.33717234, 0.57648856],
        [0.51544518, 0.9618319 , 0.71073413, 0.02979106],
        [0.61597434, 0.63622238, 0.11378924, 0.46695334]]))

In [83]:
print('A1 dimension', A1.ndim)

A1 dimension 1


In [84]:
print('A2 dimension', A2.ndim)
print('A3 dimension', A3.ndim)
print('A4 dimension', A4.ndim)

A2 dimension 1
A3 dimension 2
A4 dimension 2


In [85]:
print('A1 total elements:', A1.size)

A1 total elements: 4


In [86]:
print('A3 total elements:', A3.size)

A3 total elements: 6


In [87]:
print('datatype:', A1.dtype)

datatype: float64


In [88]:
print('datatype:', A4.dtype)

datatype: float64


In [89]:
print('datatype:', A2.dtype)

datatype: int32


In [90]:
print('A1 shape:', A1.shape)

A1 shape: (4,)


In [91]:
print('A2 shape:', A2.shape)

A2 shape: (10,)


In [92]:
print('A1 shape:', A4.shape)

A1 shape: (4, 4)


In [93]:
print('A3 shape:', A3.shape)

A3 shape: (2, 3)


In [94]:
def f(a, b):
    return a+b
g = lambda x, y: x**y # lambda function
Af = np.fromfunction(f, (2, 2)) # f executed over each coordinate i.e. (0,0)... (1,1)
Ag = np.fromfunction(g, (5,3)) # figure out
Af

array([[0., 1.],
       [1., 2.]])

In [95]:
Ag

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.]])

In [96]:
B1 = np.arange(10, 20) # similar to range()
B2 = np.arange(1, 4,0.1) # floating point stepping value possible
B1, B2


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
        2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
        3.6, 3.7, 3.8, 3.9]))

In [97]:
C1 = np.linspace(1, 10, 6) # 6 equally-spaced numbers between 1 and 10
C2 = np.linspace(1, 10, num=6) # named argument possible
C1, C2


(array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ]),
 array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ]))

In [98]:
D1 = np.zeros((5,5)) # 5x5 matrix filled with zeros
D2 = np.ones((3,3)) # 3x3 matrix filled with ones
D3 = np.empty((4,4)) # 4x4 matrix of arbitrary values
D1, D2, D3


(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0.17509297, 0.41572507, 0.165431  , 0.90549746],
        [0.08860702, 0.19036629, 0.33717234, 0.57648856],
        [0.51544518, 0.9618319 , 0.71073413, 0.02979106],
        [0.61597434, 0.63622238, 0.11378924, 0.46695334]]))

In [99]:
print(A1[0])
print(A2[-1])


1.0
9


In [100]:
print(A3[0][0])

1


In [101]:
print (A3[0, 0])

1


In [102]:
print(B1[5:])

[15 16 17 18 19]


In [103]:
B1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [104]:
print (B1[::2])

[10 12 14 16 18]


In [105]:
print(A3[:, 1:]) 

[[2 3]
 [5 6]]


In [106]:
A3

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
X = np.arange(2,20, 2)
print(X.shape)
X.reshape(3,3) 

(9,)


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [108]:
a = np.array([1, 2, 3, 4])
b = a.reshape(2,2)
a, b


(array([1, 2, 3, 4]),
 array([[1, 2],
        [3, 4]]))

In [109]:
print(a.max(), a.min())

4 1


In [110]:
print (a.sum(), a.mean(), a.std() )
print (b.sum(), b.mean(), b.std() )

10 2.5 1.118033988749895
10 2.5 1.118033988749895


In [111]:
print (b.sum(axis=0))
print (b.sum(axis=1)) 

[4 6]
[3 7]


In [112]:
print (b.mean(axis=1) )
print(np.median(a), np.median(b))
print (np.percentile(a, 25)) # 25th percentile = 1st quartile
print (np.percentile(a, 50)) # 50th percentile = median.
print (np.percentile(a, 75)) 

[1.5 3.5]
2.5 2.5
1.75
2.5
3.25


In [113]:
x = np.array([1, 2, 3])
y = 2
x*y


array([2, 4, 6])

In [114]:
z = np.arange(12).reshape(4,3)
print (z + np.sin(30) ) # operation with a scalar value
print (z + x) # x.shape = (3,) & z.shape = (4,3). X is broadcast.
z * np.random.rand(1, 3) 

[[-0.98803162  0.01196838  1.01196838]
 [ 2.01196838  3.01196838  4.01196838]
 [ 5.01196838  6.01196838  7.01196838]
 [ 8.01196838  9.01196838 10.01196838]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


array([[0.        , 0.07574225, 1.62499288],
       [2.61407676, 0.30296901, 4.0624822 ],
       [5.22815352, 0.53019576, 6.49997153],
       [7.84223028, 0.75742252, 8.93746085]])

In [115]:
A = np.array([1,2,3,4])
B = A # B is a reference to array A
print (id(A), id(B))
print (A is B)


2557065809328 2557065809328
True


In [116]:
B = A.copy() # B is another copy of A
print (id(A), id(B))
print (A is B)


2557065809328 2557065808272
False


In [130]:
my_array = np.arange(70)
my_array.shape = (2,7,5)
my_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [131]:
my_array.shape

(2, 7, 5)

In [132]:
D1 = np.zeros((5,5)) # 5x5 matrix filled with zeros
D2 = np.ones((3,3)) # 3x3 matrix filled with ones
D3 = np.empty((4,4)) # 4x4 matrix of arbitrary values
D1, D2, D3


(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0.17509297, 0.41572507, 0.165431  , 0.90549746],
        [0.08860702, 0.19036629, 0.33717234, 0.57648856],
        [0.51544518, 0.9618319 , 0.71073413, 0.02979106],
        [0.61597434, 0.63622238, 0.11378924, 0.46695334]]))