# **APC308 - Data Mining**

## Lab2: NumPy Practice Questions



* Write your code in the code cells given under each question.


* Save your notebook as **Lab2-NumPy-yourRegistrationNumber.ipynb**.


* Submission instructions shall be given. 


In [18]:
import numpy as np

#### 1. Create a 1D array of the first 100 integer numbers. 

In [19]:
import numpy as np
nb = np.array([num for num in range(100)])
print(nb)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 2. Create an array of integers beween 100 and 120  and display them in reverse order. 

In [20]:
nb = np.arange(100, 120)
print(nb[::-1])

[119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103 102
 101 100]


#### 3. Create a 10x10 matrix of the first 100 integer numbers. 

In [21]:
nb = np.array([i for i in range(100)])
nb.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### 4. Create three 10x10 matrices of all zeroes, all ones, and the identity matrix. 

In [22]:
nb1 = np.zeros((10,10))
nb2 = np.ones((10,10))
nb3 = np.identity(10)
nb1, nb2, nb3

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

#### 5. Create a 3x3 matrix of random floating point values. 

In [23]:
random_3_matrix_array = np.random.rand(3, 3)
print(random_3_matrix_array)

[[0.62361632 0.04491288 0.1325912 ]
 [0.63437918 0.79192905 0.31077656]
 [0.59949887 0.78810445 0.14879905]]


#### 6. Generate 10 evenly-spaced numbers between 1 and 4. 

In [24]:
nb = np.linspace(1, 4, 10)
nb

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

#### 7. Given the following array named M, slice and display just [4, 6].

In [25]:
nb = np.array([ [1,   3,  5], [2,  4 ,  6], [7, 9, 11] ])
print(nb[1:2,1:3])

[[4 6]]


#### 8. Given the above array M, slice and display the sub matrix [ [3, 5], [4, 6] ]. 

In [26]:
print(nb[0:2,1:3])


[[3 5]
 [4 6]]


#### 9. Display both the column-wise and row-wise sums of M i.e. [10, 16, 22] and [9, 12, 27] respectively. 

In [27]:
print (nb.sum(axis=0))
print (nb.sum(axis=1))

[10 16 22]
[ 9 12 27]


#### 10. Flatten M to a 1D array using appropriate  method. 

In [28]:
nb = nb.reshape([1,9])
nb

array([[ 1,  3,  5,  2,  4,  6,  7,  9, 11]])

#### 11. Find the <font color='orange'>second</font> largest number in a given matrix. Use your own matrix. 

In [29]:
x = [100, 200, 300, 150, 50]  
  
y = set(x)  
    
y.remove(max(y))  
   
print(max(y)) 

200


#### 12. Multiply a 3x2 matrix with a 2x3 matrix (in at least two ways). 

In [30]:
nb1 = np.arange(6).reshape(3,2)
nb2 = np.arange(6).reshape(2,3)
nb3= nb1.dot(nb2)
nb4= nb1 @ nb2

nb3, nb4 


(array([[ 3,  4,  5],
        [ 9, 14, 19],
        [15, 24, 33]]),
 array([[ 3,  4,  5],
        [ 9, 14, 19],
        [15, 24, 33]]))

#### 13. Given a matrix, display all its elements exceeding the median value. 

In [31]:
S = np.array([1, 2, 3, 4])
R = (np.percentile(S, 50))
for i in range(len(S)):
        if S[i] > R:
            print(S[i])


3
4


#### 14. Compute the following hypothetical value. Assume ```i```  is each element of M, ```mean``` and ```std``` are the aggregate mean and standard deviation values of M. 
$$ result = \sqrt{\frac{mean + i} {std} }  $$

In [32]:
import numpy as np
import math

S = np.array([1, 2, 3, 4])
R = S.mean() 
SR = S.std()
for i in S:
    result = math.sqrt((R + i)/SR)
    print(result)



1.7693205386531028
2.006220914929266
2.217960673794632
2.4111774595619155


#### 15. Given the following formula for a certain parameter named Mean Square Error (MSE), use NumPy to compute its value. 


$$ MSE = \frac{1}{n} \sum_{i=1}^{n}(x_i-y_i)^2 $$


In [33]:
# you are given the values of x and y below. Assume 'n' is the total no of elements.  

x = np.arange(20)
y = np.random.uniform(1, 10, 20)                        


# Mean Squared Error
MSE = np.square(np.subtract(x,y)).mean()
x,y,MSE




(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([3.36863604, 1.70734814, 5.97292234, 7.15126143, 6.2091054 ,
        3.4122434 , 6.85863048, 1.63868297, 4.15460209, 4.31444189,
        2.46376155, 4.9599109 , 3.67654065, 7.45612593, 6.48807616,
        6.50344328, 9.92139946, 8.58034876, 2.20732721, 3.63274366]),
 51.69011540340481)