In [26]:
pip install numpy

In [27]:
import numpy as np 
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split 
from sklearn.impute import SimpleImputer
from sklearn import preprocessing

In [66]:
iris = datasets.load_iris()
x = iris.data
y = iris.target
x[:5]
# x[-5:]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [44]:
x[:10,: :3]

array([[5.1, 0.2],
       [4.9, 0.2],
       [4.7, 0.2],
       [4.6, 0.2],
       [5. , 0.2],
       [5.4, 0.4],
       [4.6, 0.3],
       [5. , 0.2],
       [4.4, 0.2],
       [4.9, 0.1]])

In [42]:
x[:, 1:4]

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.2],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.6, 1.4, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3

In [16]:
# iris.feature_names
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [21]:
wine = datasets.load_wine()
wine.data
wine.target
wine.feature_names
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

# split dataset

In [54]:
x_train,x_test,y_test,y_train = train_test_split(x,y, test_size=0.4)
# x_train.shape
# y_train.shape
# x_test.shape
# y_test.shape

(90,)

# preprocessing with sklearn 

In [60]:
data = [[1,2],[np.nan,3],[4,2]]
imputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value =999)
# imputer.fit(data)
# imputer.transform(data)
imputer.fit_transform(data)

array([[  1.,   2.],
       [999.,   3.],
       [  4.,   2.]])

In [64]:
data = [[1,2],[np.nan,3],[4,5],[6,7]]
imputer_mean = SimpleImputer(missing_values=np.nan, strategy='mean', fill_value =999)
imputer_mean.fit_transform(data)



array([[1.        , 2.        ],
       [3.66666667, 3.        ],
       [4.        , 5.        ],
       [6.        , 7.        ]])

In [67]:
data = [[5,10,2],[9,np.nan,2],[7,2,4]]
impute_mode = SimpleImputer(missing_values=np.nan, strategy ='most_frequent')
impute_mode.fit_transform(data)

array([[ 5., 10.,  2.],
       [ 9.,  2.,  2.],
       [ 7.,  2.,  4.]])

# Activity

In [129]:
students =pd.read_csv('students.csv')
df_age = np.array(students['age']).reshape(-1,1)
df_age

array([[20.],
       [23.],
       [25.],
       [26.],
       [29.],
       [30.],
       [nan],
       [33.],
       [37.],
       [20.],
       [21.],
       [25.],
       [26.],
       [nan],
       [30.],
       [31.],
       [34.],
       [nan],
       [20.],
       [33.]])

In [95]:
imputer_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
students['age'] = imputer_mean.fit_transform(df_age) 

In [92]:
students

name        age  gender      genre
0     A  20.000000       0     HipHop
1     B  23.000000       0     HipHop
2     C  25.000000       0        NaN
3     D  26.000000       0       Jazz
4     E  29.000000       0       Jazz
5     F  30.000000       0       Jazz
6     G  27.235294       0  Classical
7     H  33.000000       0  Classical
8     I  37.000000       0  Classical
9     J  20.000000       1      Dance
10    K  21.000000       1        NaN
11    L  25.000000       1      Dance
12    M  26.000000       1   Acoustic
13    N  27.235294       1   Acoustic
14    O  30.000000       1   Acoustic
15    P  31.000000       1  Classical
16    Q  34.000000       1  Classical
17    R  27.235294       1  Classical
18    A  20.000000       0     HipHop
19    H  33.000000       0  Classical

In [96]:
df_genre = np.array(students['genre']).reshape(-1,1)
df_genre

array([['HipHop'],
       ['HipHop'],
       [nan],
       ['Jazz'],
       ['Jazz'],
       ['Jazz'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['Dance'],
       [nan],
       ['Dance'],
       ['Acoustic'],
       ['Acoustic'],
       ['Acoustic'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['HipHop'],
       ['Classical']], dtype=object)

In [98]:
imputer_most = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
students['genre'] = imputer_most.fit_transform(df_genre)

# Binarization

In [104]:
data = np.array([2,4,1,4.4,19,30,-1,0,-333]).reshape(-1,1)
#values above threshold converted to 1, below to 0
data_bin = preprocessing.Binarizer(threshold=3).transform(data)
data_bin

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.]])

# Encoding 

In [109]:
color = ['blue','white','orange']
le = preprocessing.LabelEncoder()
le.fit_transform(color)
# color

array([0, 2, 1], dtype=int64)

In [113]:
df_genre = np.array(students['genre']).reshape(-1,1)
df_genre

array([['HipHop'],
       ['HipHop'],
       ['Classical'],
       ['Jazz'],
       ['Jazz'],
       ['Jazz'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['Dance'],
       ['Classical'],
       ['Dance'],
       ['Acoustic'],
       ['Acoustic'],
       ['Acoustic'],
       ['Classical'],
       ['Classical'],
       ['Classical'],
       ['HipHop'],
       ['Classical']], dtype=object)

In [118]:
le = preprocessing.LabelEncoder()
le.fit_transform(genre)

array([3, 3, 1, 4, 4, 4, 1, 1, 1, 2, 1, 2, 0, 0, 0, 1, 1, 1, 3, 1])

name   age  gender      genre
0     A  20.0       0     HipHop
1     B  23.0       0     HipHop
2     C  25.0       0  Classical
3     D  26.0       0       Jazz
4     E  29.0       0       Jazz
5     F  30.0       0       Jazz
6     G  20.0       0  Classical
7     H  33.0       0  Classical
8     I  37.0       0  Classical
9     J  20.0       1      Dance
10    K  21.0       1  Classical
11    L  25.0       1      Dance
12    M  26.0       1   Acoustic
13    N  20.0       1   Acoustic
14    O  30.0       1   Acoustic
15    P  31.0       1  Classical
16    Q  34.0       1  Classical
17    R  20.0       1  Classical
18    A  20.0       0     HipHop
19    H  33.0       0  Classical

In [130]:
genre = students['genre']
le = preprocessing.LabelEncoder()
students['genre'] = le.fit_transform(genre)

In [131]:
students

name   age  gender  genre
0     A  20.0       0      3
1     B  23.0       0      3
2     C  25.0       0      5
3     D  26.0       0      4
4     E  29.0       0      4
5     F  30.0       0      4
6     G   NaN       0      1
7     H  33.0       0      1
8     I  37.0       0      1
9     J  20.0       1      2
10    K  21.0       1      5
11    L  25.0       1      2
12    M  26.0       1      0
13    N   NaN       1      0
14    O  30.0       1      0
15    P  31.0       1      1
16    Q  34.0       1      1
17    R   NaN       1      1
18    A  20.0       0      3
19    H  33.0       0      1

# Feature Scaling

In [125]:
#Maxmin scaler
data = [[4,2],[3,20],[1,0]]
scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
scaler_minmax.fit_transform(data)

array([[1.        , 0.1       ],
       [0.66666667, 1.        ],
       [0.        , 0.        ]])

# Standard Scaler

In [128]:
data = [[4,2],[3,20],[1,0]]
scaler_std = preprocessing.StandardScaler()
scaler_std.fit_transform(data)

array([[ 1.06904497, -0.59299945],
       [ 0.26726124,  1.4083737 ],
       [-1.33630621, -0.81537425]])